# layout: "default-la"
# title: "Spitz - Home of the Döner Kebab | Los Angeles | Mediterranean Street Food"
# email: "managingspitz@gmail.com"
# description: "Welcome to Spitz, home of the Döner Kebab, and Los Angeles' best choice for Mediterranean street food, falafel, craft beer, and fresh sangria. Try our fries, sandwiches, and wraps!"
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://eatatspitz.com"
# copyright: "© 2014 Spitz - Home of the Döner Kebab<br>All Rights Reserved."
# Build settings
# markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock","*.sublime-*","WORKFLOW.md"]
# gems: ["octopress-autoprefixer"]
logo: "assets/images/logo_new.png"
logo_no_words: "assets/images/logo_no_words.png"
seal: "assets/images/seal.png"
defaults: 
  -
    scope:
      path: "la"
    values:
      layout: "default-la"
      title: "Spitz - Home of the Döner Kebab | Los Angeles |  Mediterranean Street Food"
      email: "managingspitz@gmail.com"
      description: "Welcome to Spitz, home of the Döner Kebab, and Los Angeles' best choice for Mediterranean street food, falafel, craft beer, and fresh sangria. Try our fries, sandwiches, and wraps!"
      # description: > 
      #   Write an awesome description for your new site here. You can edit this
      #   line in _config.yml. It will appear in your document head meta (for
      #   Google search results) and in your feed.xml site description.
      baseurl: "" # the subpath of your site, e.g. /blog/
      url: "http://eatatspitz.com"
      copyright: "© 2014 Spitz - Home of the Döner Kebab<br>All Rights Reserved."
  -
    scope:
      path: "slc"
    values:
      layout: "default-slc"
      title: "Spitz SLC - Home of the Doner Kebab - Restaurant in Salt Lake City, UT"
      description: "Welcome to Spitz, home of the Döner Kebab, and Salt Lake City's best choice for Mediterranean street food, falafel, craft beer, and fresh sangria. Try our fries, sandwiches, and wraps!"
      email: "info@spitzslc.com"
      order-sugarhouse-link: "//eat24hrs.com/restaurants/order2/menu.php?id=53313"
      order-downtown-link: "//www.2lazy4food.com/#!ourfavorites/nwjoc"
      # description: > 
      #   Write an awesome description for your new site here. You can edit this
      #   line in _config.yml. It will appear in your document head meta (for
      #   Google search results) and in your feed.xml site description.
      baseurl: "" # the subpath of your site, e.g. /blog/
      url: "http://spitzslc.com"
      copyright: "© 2014 Spitz - Home of the Döner Kebab<br>All Rights Reserved."
  -
    scope:
      path: "minnesota"
    values:
      layout: "default-minnesota"
      title: "Spitz SLC - Home of the Doner Kebab - Restaurant in St. Paul, MN"
      description: "Welcome to Spitz, home of the Döner Kebab, and St. Paul's best choice for Mediterranean street food, falafel, craft beer, and fresh sangria. Try our fries, sandwiches, and wraps!"
      email: "****"
      front-photos:
        - {path: index/wrap.jpg}
        - {path: index/salad.jpg}
        - {path: index/sangria.jpg}
        - {path: index/falafel-and-veggies.jpg}
        - {path: index/vinyl-dj.jpg}
        - {path: index/KegWall.jpg}
        - {path: index/fries.jpg}
        - {path: index/wraps-and-fries.jpg}
        - {path: index/wraps.jpg}
        - {path: index/patrons.jpg}
        - {path: index/your-order.jpg}
        - {path: index/Rox4y.jpg}
        - {path: index/dj.jpg}
        - {path: index/your-order.jpg}
        - {path: index/Spitz_LT2_Aug-99.jpg}
      front-photos-mobile:
        - {path: index/mobile/wrap.jpg}
        - {path: index/mobile/salad.jpg}
        - {path: index/mobile/sangria.jpg}
        - {path: index/mobile/falafel-and-veggies.jpg}
        - {path: index/mobile/vinyl-dj.jpg}
        - {path: index/mobile/KegWall.jpg}
        - {path: index/mobile/fries.jpg}
        - {path: index/mobile/wraps-and-fries.jpg}
        - {path: index/mobile/wraps.jpg}
        - {path: index/mobile/patrons.jpg}
        - {path: index/mobile/your-order.jpg}
        - {path: index/mobile/Rox4y.jpg}
        - {path: index/mobile/dj.jpg}
        - {path: index/mobile/your-order.jpg}
        - {path: index/mobile/Spitz_LT2_Aug-99.jpg}
      # description: > 
      #   Write an awesome description for your new site here. You can edit this
      #   line in _config.yml. It will appear in your document head meta (for
      #   Google search results) and in your feed.xml site description.
      baseurl: "" # the subpath of your site, e.g. /blog/
      url: "http://spitzslc.com"
      copyright: "© 2014 Spitz - Home of the Döner Kebab<br>All Rights Reserved."
  -
    scope:
      path: "san_diego"
    values:
      layout: "default-la"
      title: "Spitz SLC - Home of the Doner Kebab - Restaurant in St. Paul, MN"
      description: "Welcome to Spitz, home of the Döner Kebab, and St. Paul's best choice for Mediterranean street food, falafel, craft beer, and fresh sangria. Try our fries, sandwiches, and wraps!"
      email: "****"
      front-photos:
        - {path: assets/images/slider/index/mobile/wraps.jpg}
        - {path: assets/images/slider/index/mobile/wraps-and-fries.jpg}
        - {path: assets/images/slider/index/mobile/falafel-and-veggies.jpg}
        - {path: assets/images/slider/index/mobile/vinyl-dj.jpg}
        - {path: assets/images/slider/index/mobile/sangria.jpg}
        - {path: assets/images/slider/index/mobile/salad.jpg}
        - {path: assets/images/slider/index/mobile/wrap.jpg}
        - {path: assets/images/slider/index/mobile/KegWall.jpg}
        - {path: assets/images/slider/index/mobile/beer-taps.jpg}
        - {path: assets/images/slider/index/mobile/fries.jpg}
        - {path: assets/images/slider/index/mobile/dj.jpg}
        - {path: assets/images/slider/index/mobile/your-order.jpg}
        - {path: assets/images/slider/index/mobile/dj.jpg}
        - {path: assets/images/slider/index/mobile/patrons.jpg}
      front-photos-mobile:
        - {path: assets/images/slider/index/mobile/wraps.jpg}
        - {path: assets/images/slider/index/mobile/wraps-and-fries.jpg}
        - {path: assets/images/slider/index/mobile/falafel-and-veggies.jpg}
        - {path: assets/images/slider/index/mobile/vinyl-dj.jpg}
        - {path: assets/images/slider/index/mobile/sangria.jpg}
        - {path: assets/images/slider/index/mobile/salad.jpg}
        - {path: assets/images/slider/index/mobile/wrap.jpg}
        - {path: assets/images/slider/index/mobile/KegWall.jpg}
        - {path: assets/images/slider/index/mobile/beer-taps.jpg}
        - {path: assets/images/slider/index/mobile/fries.jpg}
        - {path: assets/images/slider/index/mobile/dj.jpg}
        - {path: assets/images/slider/index/mobile/your-order.jpg}
        - {path: assets/images/slider/index/mobile/dj.jpg}
        - {path: assets/images/slider/index/mobile/patrons.jpg}
      # description: > 
      #   Write an awesome description for your new site here. You can edit this
      #   line in _config.yml. It will appear in your document head meta (for
      #   Google search results) and in your feed.xml site description.
      baseurl: "" # the subpath of your site, e.g. /blog/
      url: "http://spitzslc.com"
      copyright: "© 2014 Spitz - Home of the Döner Kebab<br>All Rights Reserved."
